### ISSUE TITLE
How are you handling savedInstanceState ?

### ISSUE THREAD

**Issue by Zeyad-37** [oldergod/android-architecture#25]
I really like your implementation of MVI, but i was wondering what do you about savedInstanceState ? because i havent seen any code that managing that.

**Comment by oldergod** [comment]
Hey Zeyad, you're right.
At the moment, there is no code that manage data through `savedInstanceState `. When I ported the TODO app to the MVI implementation, I didn't change the functionality the original repository supported and it didn't include this part.

**Comment by Zeyad-37** [comment]
Great thanks, I will give some thought to it and let you know if i come up with something
