### ISSUE TITLE
ViewModel must never reference a view

### ISSUE THREAD

**Issue by dmytrodanylyk** [oldergod/android-architecture#38]
Hi,

The official Android [documentation](https://developer.android.com/topic/libraries/architecture/viewmodel) says:

> Caution: A ViewModel must never reference a view, Lifecycle, or any class that may hold a reference to the activity context.

I didn't dive deeply into MVI architecture and your code yet, but looks like View Model is observing events from Activty, which means it has a reference to activty. 

Is it done intentional?

**Comment by oldergod** [comment]
Indeed, the ViewModel which would outlive the activity, could prevent the latter to be garbage collected and then would start leaking memory.
When destroyed, the activity or fragment terminates its streams and unsubscribe from the ViewModel so no problem here.
