### ISSUE TITLE
Crash on add TODO item

### ISSUE THREAD

**Issue by tellypresence** [oldergod/android-architecture#39]
Easily reproduced:
* launch app
* add TODO item with title and description
* clicking OK button will trigger crash
```
com.example.android.architecture.blueprints.todomvp.mock E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.architecture.blueprints.todomvp.mock, PID: 18516
    io.reactivex.exceptions.OnErrorNotImplementedException: no such table: tasks (code 1): , while compiling: INSERT OR REPLACE  INTO tasks(completed,description,title,entryid) VALUES (?,?,?,?)
```

**Comment by oldergod** [comment]
Hey, thank you for the report.
Was branch were you testing on? I don't think we have any file packaged under `com.example.android.architecture.blueprints.todomvp.mock`.

Are you sure it's not one of the branch of the parent project here? https://github.com/googlesamples/android-architecture

**Comment by tellypresence** [comment]
Apologies, your app is not at fault.  The problem was that I had a different variant
(might have been mvvm-rx or mvp-coroutines etc) which had a slightly different DB
schema, so when I installed your app over that one it crashed.

Simply uninstalling the apk, then relaunching your app works perfectly.

(Fix could be as simple as appending e.g. ".mvi" to android.defaultConfig.applicationId)
