### ISSUE TITLE
Making Rxjava Stream Lifecycle aware 

### ISSUE THREAD

**Issue by goransipic** [oldergod/android-architecture#42]
Hi,

thanks for great example of using Mvi with RxJava. In your examples you are handling subscription manually but there is more elegant way with [Auto Dispose library](https://github.com/uber/AutoDispose).

**Comment by oldergod** [comment]
Thank you for letting me know. Feel free to use it in your own project.
I don't think it adds any value to this sample's purpose so I won't add it though.
