### ISSUE TITLE
How to handle realtime data subscriber

### ISSUE THREAD

**Issue by watsaponk** [oldergod/android-architecture#63]
Example : Chat Application that message can come anytime
I should subscribe to realtime data source on Fragment or ViewModel ?
if I subscribe on ViewModel so it ok or not to call intent inside ViewModel?

Thank yoy

**Comment by oldergod** [comment]
Any new emission should generate a new view model. You could receive a push notification which would update a DB which the presenter could react on.

**Comment by watsaponk** [comment]
![mvi_realtime-data](https://user-images.githubusercontent.com/51149687/70677977-4d577880-1cc3-11ea-8de0-b753411f7495.jpg)

Am i understand correctly ?

**Comment by oldergod** [comment]
A processor should be the one hitting the network or the cache or whatever it is. Otherwise, yes.

**Comment by watsaponk** [comment]
thank you @oldergod :)
